"""Curated seed data for known Exchange/VASP, Mixer, Bridge, and Flagged addresses.

Complies with forensic provenance and accuracy requirements:
- Source references and official government / block-explorer citations
- Verified dates reflect actual historical disclosure/designation dates
- Strict separation between verified sources and unverified community records
- Entries unconfirmed by official regulatory disclosure or formal exchange PoR are marked as unverified / demo data
"""

from backend.schemas.attribution import AddressLabel, EntityCategory, VerificationStatus

SEED_VERIFIED_LABELS: list[AddressLabel] = [
    # --- Ethereum Exchanges (VASP) ---
    AddressLabel(
        id="eth-binance-hot-14",
        chain="ethereum",
        address="0x28c6c06298d514db089934071355e5743bf21d60",
        entity_name="Binance Hot Wallet 14",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="Etherscan Official Directory & Public Proof of Reserves",
        source_url="https://etherscan.io/address/0x28c6c06298d514db089934071355e5743bf21d60",
        confidence=0.99,
        verified_at="2021-05-19T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="High-volume Binance custodial hot wallet. Frequently receives retail deposits.",
    ),
    AddressLabel(
        id="eth-coinbase-10",
        chain="ethereum",
        address="0x503828976d22510aad0201ac7ec88293211d23da",
        entity_name="Coinbase 10",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="Coinbase Public Disclosures & Etherscan",
        source_url="https://etherscan.io/address/0x503828976d22510aad0201ac7ec88293211d23da",
        confidence=0.99,
        verified_at="2021-08-01T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Coinbase primary settlement exchange wallet.",
    ),
    AddressLabel(
        id="eth-kraken-1",
        chain="ethereum",
        address="0x2910543af39aba0cd09dbb2d50200b3e800a63d2",
        entity_name="Kraken Exchange 1",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="Kraken Operational Disclosures & Etherscan",
        source_url="https://etherscan.io/address/0x2910543af39aba0cd09dbb2d50200b3e800a63d2",
        confidence=0.98,
        verified_at="2021-06-15T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Kraken operational hot wallet.",
    ),

    # --- Ethereum Mixers & Privacy Protocols (OFAC Designated) ---
    AddressLabel(
        id="eth-tornado-router",
        chain="ethereum",
        address="0xd90e2f925da726b50c4ed8d0fb90ad053324f31b",
        entity_name="Tornado.Cash: Router",
        entity_category=EntityCategory.MIXER,
        source="OFAC SDN Sanctions List / US Treasury",
        source_url="https://sanctionssearch.ofac.treas.gov/",
        confidence=1.0,
        verified_at="2022-08-08T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Decentralized privacy mixer router contract. Designated on OFAC SDN list.",
    ),
    AddressLabel(
        id="eth-tornado-10eth",
        chain="ethereum",
        address="0x910cbd523d972eb0a6f4cae4618ad62622b39dbf",
        entity_name="Tornado.Cash: 10 ETH Pool",
        entity_category=EntityCategory.MIXER,
        source="OFAC SDN Sanctions List / US Treasury",
        source_url="https://sanctionssearch.ofac.treas.gov/",
        confidence=1.0,
        verified_at="2022-08-08T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Tornado Cash 10 ETH fixed denomination zero-knowledge privacy pool.",
    ),
    AddressLabel(
        id="eth-tornado-100eth",
        chain="ethereum",
        address="0xa160cdab225685da1d56aa342ad8841c3b53f291",
        entity_name="Tornado.Cash: 100 ETH Pool",
        entity_category=EntityCategory.MIXER,
        source="OFAC SDN Sanctions List / US Treasury",
        source_url="https://sanctionssearch.ofac.treas.gov/",
        confidence=1.0,
        verified_at="2022-08-08T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Tornado Cash 100 ETH fixed denomination pool (OFAC designated).",
    ),

    # --- Illicit Flagged / Sanctioned Wallets ---
    AddressLabel(
        id="eth-lazarus-ronin",
        chain="ethereum",
        address="0x098b716b8aaf21512996dc57eb0615e2383e2f96",
        entity_name="Lazarus Group Associated (Ronin Exploiter)",
        entity_category=EntityCategory.SANCTIONED,
        source="FBI & OFAC Cyber-Related Sanctions",
        source_url="https://home.treasury.gov/news/press-releases/jy0715",
        confidence=1.0,
        verified_at="2022-04-14T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Designated by US Treasury OFAC in connection with Lazarus Group Ronin Validator theft.",
    ),

    # --- Bitcoin Addresses (Verified Cold Storage & OFAC Mixer) ---
    AddressLabel(
        id="btc-binance-cold",
        chain="bitcoin",
        address="34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
        entity_name="Binance Bitcoin Cold Storage",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="Binance Public Proof of Reserves & BitInfoCharts",
        source_url="https://bitinfocharts.com/bitcoin/address/34xp4vRoCGJym3xR7yCVPFHoCNxv4Twseo",
        confidence=0.99,
        verified_at="2022-11-10T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Major Binance BTC reserve storage address documented in public reserve disclosures.",
    ),
    AddressLabel(
        id="btc-sinbad-mixer-1",
        chain="bitcoin",
        address="bc1qq7p0es3dv5hcynjjf40f2xjjr6qp5py47d2f6n847vduuq9gvnyq7y9ecd",
        entity_name="Sinbad.io Mixer Main Pool",
        entity_category=EntityCategory.MIXER,
        source="OFAC SDN Sanctions List / US Treasury Release jy1934",
        source_url="https://home.treasury.gov/news/press-releases/jy1934",
        confidence=1.0,
        verified_at="2023-11-29T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="OFAC designated Bitcoin mixer used for laundering proceeds from cyber intrusions (Treasury Action jy1934).",
    ),
    AddressLabel(
        id="btc-sinbad-mixer-2",
        chain="bitcoin",
        address="1JHdQHkBZiim1cb4hyUh2PbzEbbg6z2TrF",
        entity_name="Sinbad.io Mixer Secondary Hub",
        entity_category=EntityCategory.MIXER,
        source="OFAC SDN Sanctions List / US Treasury Release jy1934",
        source_url="https://home.treasury.gov/news/press-releases/jy1934",
        confidence=1.0,
        verified_at="2023-11-29T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="OFAC designated Bitcoin mixer settlement address (Treasury Action jy1934).",
    ),

    # --- TRON Addresses (Verified via TronScan Explorer Tag) ---
    AddressLabel(
        id="trx-binance-cold-2",
        chain="tron",
        address="TWd4WrZ9wn84f5x1hZhL4DHvk738ns5jwb",
        entity_name="Binance-Cold 2 (TRON)",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="TronScan Verified Public Label (Binance-Cold 2)",
        source_url="https://tronscan.org/#/address/TWd4WrZ9wn84f5x1hZhL4DHvk738ns5jwb",
        confidence=0.98,
        verified_at="2022-03-01T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Binance Cold Storage wallet 2 on TRON, confirmed via TronScan Name Tag directory.",
    ),

    # --- BNB Smart Chain (BSC) ---
    AddressLabel(
        id="bsc-binance-hot",
        chain="bsc",
        address="0x8894e0a0c962cb723c1976a4421c95949be2d4e3",
        entity_name="Binance BSC Hot Wallet 6",
        entity_category=EntityCategory.EXCHANGE_VASP,
        source="BscScan Verified Contract & Exchange Label",
        source_url="https://bscscan.com/address/0x8894e0a0c962cb723c1976a4421c95949be2d4e3",
        confidence=0.99,
        verified_at="2022-05-15T00:00:00Z",
        verification_status=VerificationStatus.VERIFIED,
        notes="Binance BSC custodial wallet gateway.",
    ),
]

SEED_UNVERIFIED_COMMUNITY_LABELS: list[AddressLabel] = [
    AddressLabel(
        id="eth-community-reported-phishing",
        chain="ethereum",
        address="0x71c8564a59f0f9b6a1240173693e5077464d621e",
        entity_name="Reported Phishing Originator (Demo Subject)",
        entity_category=EntityCategory.SCAM_FRAUD,
        source="Community Phishing Report #49102",
        source_url="https://cryptoscamdb.org/",
        confidence=0.50,
        verified_at=None,
        verification_status=VerificationStatus.UNVERIFIED_COMMUNITY,
        notes="Unverified community report of unauthorized draining. Retained as demo test subject.",
    ),
    AddressLabel(
        id="eth-community-highrisk-drainer",
        chain="ethereum",
        address="0x844e211e291077b11221c0f18615fe643202c35c",
        entity_name="Suspected Phishing Drainer Contract",
        entity_category=EntityCategory.HIGH_RISK,
        source="Public Scam Sniffer Community Warning",
        source_url="https://twitter.com/realScamSniffer",
        confidence=0.55,
        verified_at=None,
        verification_status=VerificationStatus.UNVERIFIED_COMMUNITY,
        notes="Community flagged phishing drainer. Lacks official regulatory sanction.",
    ),
    AddressLabel(
        id="trx-demo-unverified-wtrx",
        chain="tron",
        address="TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",
        entity_name="Wrapped TRX Contract (Demo Unverified)",
        entity_category=EntityCategory.DEFI_PROTOCOL,
        source="TronScan Contract Directory",
        source_url="https://tronscan.org/#/address/TNUC9Qb1rRpS5CbWLmNMxXBjyFoydXjWFR",
        confidence=0.60,
        verified_at=None,
        verification_status=VerificationStatus.UNVERIFIED_COMMUNITY,
        notes="DeFi Wrapped TRX token contract. Lacks VASP status.",
    ),
]
